// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package types

import (
	"fmt"
	"strings"
)

const (
	// DNSRecordStrategyAll is a DNSRecordStrategy of type all.
	DNSRecordStrategyAll DNSRecordStrategy = "all"
	// DNSRecordStrategyRoundRobin is a DNSRecordStrategy of type round-robin.
	DNSRecordStrategyRoundRobin DNSRecordStrategy = "round-robin"
	// DNSRecordStrategyRebind is a DNSRecordStrategy of type rebind.
	DNSRecordStrategyRebind DNSRecordStrategy = "rebind"
)

var ErrInvalidDNSRecordStrategy = fmt.Errorf("not a valid DNSRecordStrategy, try [%s]", strings.Join(_DNSRecordStrategyNames, ", "))

var _DNSRecordStrategyNames = []string{
	string(DNSRecordStrategyAll),
	string(DNSRecordStrategyRoundRobin),
	string(DNSRecordStrategyRebind),
}

// DNSRecordStrategyNames returns a list of possible string values of DNSRecordStrategy.
func DNSRecordStrategyNames() []string {
	tmp := make([]string, len(_DNSRecordStrategyNames))
	copy(tmp, _DNSRecordStrategyNames)
	return tmp
}

// DNSRecordStrategyValues returns a list of the values for DNSRecordStrategy
func DNSRecordStrategyValues() []DNSRecordStrategy {
	return []DNSRecordStrategy{
		DNSRecordStrategyAll,
		DNSRecordStrategyRoundRobin,
		DNSRecordStrategyRebind,
	}
}

// String implements the Stringer interface.
func (x DNSRecordStrategy) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x DNSRecordStrategy) IsValid() bool {
	_, err := ParseDNSRecordStrategy(string(x))
	return err == nil
}

var _DNSRecordStrategyValue = map[string]DNSRecordStrategy{
	"all":         DNSRecordStrategyAll,
	"round-robin": DNSRecordStrategyRoundRobin,
	"rebind":      DNSRecordStrategyRebind,
}

// ParseDNSRecordStrategy attempts to convert a string to a DNSRecordStrategy.
func ParseDNSRecordStrategy(name string) (DNSRecordStrategy, error) {
	if x, ok := _DNSRecordStrategyValue[name]; ok {
		return x, nil
	}
	return DNSRecordStrategy(""), fmt.Errorf("%s is %w", name, ErrInvalidDNSRecordStrategy)
}

func (x DNSRecordStrategy) Ptr() *DNSRecordStrategy {
	return &x
}

const (
	// DNSRecordTypeA is a DNSRecordType of type A.
	DNSRecordTypeA DNSRecordType = "A"
	// DNSRecordTypeAAAA is a DNSRecordType of type AAAA.
	DNSRecordTypeAAAA DNSRecordType = "AAAA"
	// DNSRecordTypeMX is a DNSRecordType of type MX.
	DNSRecordTypeMX DNSRecordType = "MX"
	// DNSRecordTypeTXT is a DNSRecordType of type TXT.
	DNSRecordTypeTXT DNSRecordType = "TXT"
	// DNSRecordTypeCNAME is a DNSRecordType of type CNAME.
	DNSRecordTypeCNAME DNSRecordType = "CNAME"
	// DNSRecordTypeNS is a DNSRecordType of type NS.
	DNSRecordTypeNS DNSRecordType = "NS"
	// DNSRecordTypeCAA is a DNSRecordType of type CAA.
	DNSRecordTypeCAA DNSRecordType = "CAA"
)

var ErrInvalidDNSRecordType = fmt.Errorf("not a valid DNSRecordType, try [%s]", strings.Join(_DNSRecordTypeNames, ", "))

var _DNSRecordTypeNames = []string{
	string(DNSRecordTypeA),
	string(DNSRecordTypeAAAA),
	string(DNSRecordTypeMX),
	string(DNSRecordTypeTXT),
	string(DNSRecordTypeCNAME),
	string(DNSRecordTypeNS),
	string(DNSRecordTypeCAA),
}

// DNSRecordTypeNames returns a list of possible string values of DNSRecordType.
func DNSRecordTypeNames() []string {
	tmp := make([]string, len(_DNSRecordTypeNames))
	copy(tmp, _DNSRecordTypeNames)
	return tmp
}

// DNSRecordTypeValues returns a list of the values for DNSRecordType
func DNSRecordTypeValues() []DNSRecordType {
	return []DNSRecordType{
		DNSRecordTypeA,
		DNSRecordTypeAAAA,
		DNSRecordTypeMX,
		DNSRecordTypeTXT,
		DNSRecordTypeCNAME,
		DNSRecordTypeNS,
		DNSRecordTypeCAA,
	}
}

// String implements the Stringer interface.
func (x DNSRecordType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x DNSRecordType) IsValid() bool {
	_, err := ParseDNSRecordType(string(x))
	return err == nil
}

var _DNSRecordTypeValue = map[string]DNSRecordType{
	"A":     DNSRecordTypeA,
	"AAAA":  DNSRecordTypeAAAA,
	"MX":    DNSRecordTypeMX,
	"TXT":   DNSRecordTypeTXT,
	"CNAME": DNSRecordTypeCNAME,
	"NS":    DNSRecordTypeNS,
	"CAA":   DNSRecordTypeCAA,
}

// ParseDNSRecordType attempts to convert a string to a DNSRecordType.
func ParseDNSRecordType(name string) (DNSRecordType, error) {
	if x, ok := _DNSRecordTypeValue[name]; ok {
		return x, nil
	}
	return DNSRecordType(""), fmt.Errorf("%s is %w", name, ErrInvalidDNSRecordType)
}

func (x DNSRecordType) Ptr() *DNSRecordType {
	return &x
}
