// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package types

import (
	"fmt"
	"strings"
)

const (
	// EventProtocolDns is a EventProtocol of type dns.
	EventProtocolDns EventProtocol = "dns"
	// EventProtocolHttp is a EventProtocol of type http.
	EventProtocolHttp EventProtocol = "http"
	// EventProtocolHttps is a EventProtocol of type https.
	EventProtocolHttps EventProtocol = "https"
	// EventProtocolSmtp is a EventProtocol of type smtp.
	EventProtocolSmtp EventProtocol = "smtp"
	// EventProtocolFtp is a EventProtocol of type ftp.
	EventProtocolFtp EventProtocol = "ftp"
)

var ErrInvalidEventProtocol = fmt.Errorf("not a valid EventProtocol, try [%s]", strings.Join(_EventProtocolNames, ", "))

var _EventProtocolNames = []string{
	string(EventProtocolDns),
	string(EventProtocolHttp),
	string(EventProtocolHttps),
	string(EventProtocolSmtp),
	string(EventProtocolFtp),
}

// EventProtocolNames returns a list of possible string values of EventProtocol.
func EventProtocolNames() []string {
	tmp := make([]string, len(_EventProtocolNames))
	copy(tmp, _EventProtocolNames)
	return tmp
}

// EventProtocolValues returns a list of the values for EventProtocol
func EventProtocolValues() []EventProtocol {
	return []EventProtocol{
		EventProtocolDns,
		EventProtocolHttp,
		EventProtocolHttps,
		EventProtocolSmtp,
		EventProtocolFtp,
	}
}

// String implements the Stringer interface.
func (x EventProtocol) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x EventProtocol) IsValid() bool {
	_, err := ParseEventProtocol(string(x))
	return err == nil
}

var _EventProtocolValue = map[string]EventProtocol{
	"dns":   EventProtocolDns,
	"http":  EventProtocolHttp,
	"https": EventProtocolHttps,
	"smtp":  EventProtocolSmtp,
	"ftp":   EventProtocolFtp,
}

// ParseEventProtocol attempts to convert a string to a EventProtocol.
func ParseEventProtocol(name string) (EventProtocol, error) {
	if x, ok := _EventProtocolValue[name]; ok {
		return x, nil
	}
	return EventProtocol(""), fmt.Errorf("%s is %w", name, ErrInvalidEventProtocol)
}

func (x EventProtocol) Ptr() *EventProtocol {
	return &x
}
