// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_records.sql

package database

import (
	"context"
	"time"
)

const auditRecordsCreate = `-- name: AuditRecordsCreate :one
INSERT INTO audit_records (
  action,
  resource_type,
  source,
  actor_id,
  actor_name,
  actor_metadata,
  resource
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
RETURNING id, uuid, created_at, action, resource_type, source, actor_id, actor_name, actor_metadata, resource
`

type AuditRecordsCreateParams struct {
	Action        AuditRecordActionType   `db:"action"`
	ResourceType  AuditRecordResourceType `db:"resource_type"`
	Source        AuditRecordSourceType   `db:"source"`
	ActorID       *int64                  `db:"actor_id"`
	ActorName     string                  `db:"actor_name"`
	ActorMetadata AuditActorMetadata      `db:"actor_metadata"`
	Resource      AuditResource           `db:"resource"`
}

func (q *Queries) AuditRecordsCreate(ctx context.Context, arg AuditRecordsCreateParams) (*AuditRecord, error) {
	row := q.db.QueryRow(ctx, auditRecordsCreate,
		arg.Action,
		arg.ResourceType,
		arg.Source,
		arg.ActorID,
		arg.ActorName,
		arg.ActorMetadata,
		arg.Resource,
	)
	var i AuditRecord
	err := row.Scan(
		&i.ID,
		&i.UUID,
		&i.CreatedAt,
		&i.Action,
		&i.ResourceType,
		&i.Source,
		&i.ActorID,
		&i.ActorName,
		&i.ActorMetadata,
		&i.Resource,
	)
	return &i, err
}

const auditRecordsGetByID = `-- name: AuditRecordsGetByID :one
SELECT id, uuid, created_at, action, resource_type, source, actor_id, actor_name, actor_metadata, resource FROM audit_records WHERE id = $1
`

func (q *Queries) AuditRecordsGetByID(ctx context.Context, id int64) (*AuditRecord, error) {
	row := q.db.QueryRow(ctx, auditRecordsGetByID, id)
	var i AuditRecord
	err := row.Scan(
		&i.ID,
		&i.UUID,
		&i.CreatedAt,
		&i.Action,
		&i.ResourceType,
		&i.Source,
		&i.ActorID,
		&i.ActorName,
		&i.ActorMetadata,
		&i.Resource,
	)
	return &i, err
}

const auditRecordsList = `-- name: AuditRecordsList :many
SELECT id, uuid, created_at, action, resource_type, source, actor_id, actor_name, actor_metadata, resource FROM audit_records
WHERE
  ($1::bigint IS NULL OR actor_id = $1::bigint)
  AND ($2::text = '' OR actor_name = $2::text)
  AND ($3::text = '' OR resource_type::text = $3::text)
  AND ($4::text = '' OR action::text = $4::text)
  AND ($5::timestamptz IS NULL OR created_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR created_at <= $6::timestamptz)
ORDER BY id DESC
LIMIT $8
OFFSET $7
`

type AuditRecordsListParams struct {
	ActorID      *int64     `db:"actor_id"`
	ActorName    string     `db:"actor_name"`
	ResourceType string     `db:"resource_type"`
	Action       string     `db:"action"`
	FromAt       *time.Time `db:"from_at"`
	ToAt         *time.Time `db:"to_at"`
	PageOffset   int64      `db:"page_offset"`
	PageLimit    int64      `db:"page_limit"`
}

func (q *Queries) AuditRecordsList(ctx context.Context, arg AuditRecordsListParams) ([]*AuditRecord, error) {
	rows, err := q.db.Query(ctx, auditRecordsList,
		arg.ActorID,
		arg.ActorName,
		arg.ResourceType,
		arg.Action,
		arg.FromAt,
		arg.ToAt,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*AuditRecord{}
	for rows.Next() {
		var i AuditRecord
		if err := rows.Scan(
			&i.ID,
			&i.UUID,
			&i.CreatedAt,
			&i.Action,
			&i.ResourceType,
			&i.Source,
			&i.ActorID,
			&i.ActorName,
			&i.ActorMetadata,
			&i.Resource,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
