// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_records.sql

package database

import (
	"context"
	"time"
)

const auditRecordsCreate = `-- name: AuditRecordsCreate :one
INSERT INTO audit_records (
  operation,
  actor,
  target,
  data
)
VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING id, operation, actor, target, data, created_at
`

type AuditRecordsCreateParams struct {
	Operation AuditRecordOperationType `db:"operation"`
	Actor     AuditActor               `db:"actor"`
	Target    AuditTarget              `db:"target"`
	Data      AuditData                `db:"data"`
}

func (q *Queries) AuditRecordsCreate(ctx context.Context, arg AuditRecordsCreateParams) (*AuditRecord, error) {
	row := q.db.QueryRow(ctx, auditRecordsCreate,
		arg.Operation,
		arg.Actor,
		arg.Target,
		arg.Data,
	)
	var i AuditRecord
	err := row.Scan(
		&i.ID,
		&i.Operation,
		&i.Actor,
		&i.Target,
		&i.Data,
		&i.CreatedAt,
	)
	return &i, err
}

const auditRecordsGetByID = `-- name: AuditRecordsGetByID :one
SELECT id, operation, actor, target, data, created_at FROM audit_records WHERE id = $1
`

func (q *Queries) AuditRecordsGetByID(ctx context.Context, id int64) (*AuditRecord, error) {
	row := q.db.QueryRow(ctx, auditRecordsGetByID, id)
	var i AuditRecord
	err := row.Scan(
		&i.ID,
		&i.Operation,
		&i.Actor,
		&i.Target,
		&i.Data,
		&i.CreatedAt,
	)
	return &i, err
}

const auditRecordsList = `-- name: AuditRecordsList :many
SELECT id, operation, actor, target, data, created_at FROM audit_records
WHERE
  ($1::bigint IS NULL OR NULLIF(actor->>'id', '')::bigint = $1::bigint)
  AND ($2::text = '' OR actor->>'name' = $2::text)
  AND ($3::text = '' OR target->>'type' = $3::text)
  AND ($4::bigint IS NULL OR NULLIF(target->>'id', '')::bigint = $4::bigint)
  AND ($5::text = '' OR target->>'key' = $5::text)
  AND ($6::text = '' OR operation::text = $6::text)
  AND ($7::bigint IS NULL OR NULLIF(target->>'payload_id', '')::bigint = $7::bigint)
  AND ($8::text = '' OR target->>'payload_name' = $8::text)
  AND ($9::timestamptz IS NULL OR created_at >= $9::timestamptz)
  AND ($10::timestamptz IS NULL OR created_at <= $10::timestamptz)
ORDER BY id DESC
LIMIT $12
OFFSET $11
`

type AuditRecordsListParams struct {
	ActorID      *int64     `db:"actor_id"`
	ActorName    string     `db:"actor_name"`
	ResourceType string     `db:"resource_type"`
	ResourceID   *int64     `db:"resource_id"`
	ResourceKey  string     `db:"resource_key"`
	Action       string     `db:"action"`
	PayloadID    *int64     `db:"payload_id"`
	PayloadName  string     `db:"payload_name"`
	FromAt       *time.Time `db:"from_at"`
	ToAt         *time.Time `db:"to_at"`
	PageOffset   int64      `db:"page_offset"`
	PageLimit    int64      `db:"page_limit"`
}

func (q *Queries) AuditRecordsList(ctx context.Context, arg AuditRecordsListParams) ([]*AuditRecord, error) {
	rows, err := q.db.Query(ctx, auditRecordsList,
		arg.ActorID,
		arg.ActorName,
		arg.ResourceType,
		arg.ResourceID,
		arg.ResourceKey,
		arg.Action,
		arg.PayloadID,
		arg.PayloadName,
		arg.FromAt,
		arg.ToAt,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*AuditRecord{}
	for rows.Next() {
		var i AuditRecord
		if err := rows.Scan(
			&i.ID,
			&i.Operation,
			&i.Actor,
			&i.Target,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
