// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	DNSRecordsCreate(ctx context.Context, arg DNSRecordsCreateParams) (*DNSRecord, error)
	DNSRecordsDelete(ctx context.Context, id *int64) error
	DNSRecordsDeleteAllByPayloadID(ctx context.Context, payloadID int64) ([]*DNSRecord, error)
	DNSRecordsDeleteAllByPayloadIDAndName(ctx context.Context, payloadID int64, name string) ([]*DNSRecord, error)
	DNSRecordsGetByID(ctx context.Context, id *int64) (*DNSRecord, error)
	DNSRecordsGetByPayloadID(ctx context.Context, payloadID int64) ([]*DNSRecord, error)
	DNSRecordsGetByPayloadIDAndIndex(ctx context.Context, payloadID int64, index int) (*DNSRecord, error)
	DNSRecordsGetByPayloadNameAndType(ctx context.Context, arg DNSRecordsGetByPayloadNameAndTypeParams) (*DNSRecord, error)
	DNSRecordsGetCountByPayloadID(ctx context.Context, payloadID int64) (int64, error)
	DNSRecordsUpdate(ctx context.Context, arg DNSRecordsUpdateParams) (*DNSRecord, error)
	EventsCreate(ctx context.Context, arg EventsCreateParams) (*Event, error)
	EventsGetByID(ctx context.Context, id int64) (*Event, error)
	EventsGetByPayloadAndIndex(ctx context.Context, payloadID int64, index int64) (*EventsGetByPayloadAndIndexRow, error)
	EventsListByPayloadID(ctx context.Context, arg EventsListByPayloadIDParams) ([]*EventsListByPayloadIDRow, error)
	HTTPRoutesCreate(ctx context.Context, arg HTTPRoutesCreateParams) (*HTTPRoute, error)
	HTTPRoutesDelete(ctx context.Context, id int64) error
	HTTPRoutesDeleteAllByPayloadID(ctx context.Context, payloadID int64) ([]*HTTPRoute, error)
	HTTPRoutesDeleteAllByPayloadIDAndPath(ctx context.Context, payloadID int64, path string) ([]*HTTPRoute, error)
	HTTPRoutesGetByID(ctx context.Context, id int64) (*HTTPRoute, error)
	HTTPRoutesGetByPayloadID(ctx context.Context, payloadID int64) ([]*HTTPRoute, error)
	HTTPRoutesGetByPayloadIDAndIndex(ctx context.Context, payloadID int64, index int) (*HTTPRoute, error)
	HTTPRoutesGetByPayloadMethodAndPath(ctx context.Context, arg HTTPRoutesGetByPayloadMethodAndPathParams) (*HTTPRoute, error)
	HTTPRoutesUpdate(ctx context.Context, arg HTTPRoutesUpdateParams) (*HTTPRoute, error)
	PayloadsCreate(ctx context.Context, arg PayloadsCreateParams) (*Payload, error)
	PayloadsDelete(ctx context.Context, id int64) (*Payload, error)
	PayloadsDeleteByNamePart(ctx context.Context, userID int64, name string) ([]*Payload, error)
	PayloadsFindByUserAndName(ctx context.Context, arg PayloadsFindByUserAndNameParams) ([]*Payload, error)
	PayloadsFindByUserID(ctx context.Context, userID int64) ([]*Payload, error)
	PayloadsGetAllSubdomains(ctx context.Context) ([]string, error)
	PayloadsGetByID(ctx context.Context, id int64) (*Payload, error)
	PayloadsGetBySubdomain(ctx context.Context, subdomain string) (*Payload, error)
	PayloadsGetByUserAndName(ctx context.Context, userID int64, name string) (*Payload, error)
	PayloadsUpdate(ctx context.Context, arg PayloadsUpdateParams) (*Payload, error)
	UsersDelete(ctx context.Context, id int64) error
	UsersGetByID(ctx context.Context, id int64) (*UsersFull, error)
	UsersGetByName(ctx context.Context, name string) (*UsersFull, error)
	UsersGetByParam(ctx context.Context, key string, value string) (*UsersFull, error)
	UsersList(ctx context.Context) ([]*UsersFull, error)
	userParamsInsert(ctx context.Context, arg userParamsInsertParams) error
	userParamsUpdate(ctx context.Context, arg userParamsUpdateParams) error
	usersInsert(ctx context.Context, arg usersInsertParams) (*User, error)
	usersUpdate(ctx context.Context, arg usersUpdateParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
