// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
)

const usersCreate = `-- name: UsersCreate :one
INSERT INTO users (name, is_admin, created_by, api_token, telegram_id, lark_id, slack_id, created_at)
VALUES ($1, $2, $3, COALESCE(NULLIF($4, ''), encode(gen_random_bytes(16), 'hex')), $5, $6, $7, now())
RETURNING id, name, created_at, is_admin, created_by, telegram_id, slack_id, lark_id, api_token
`

type UsersCreateParams struct {
	Name       string  `db:"name"`
	IsAdmin    bool    `db:"is_admin"`
	CreatedBy  *int64  `db:"created_by"`
	APIToken   *string `db:"api_token"`
	TelegramID *int64  `db:"telegram_id"`
	LarkID     *string `db:"lark_id"`
	SlackID    *string `db:"slack_id"`
}

func (q *Queries) UsersCreate(ctx context.Context, arg UsersCreateParams) (*User, error) {
	row := q.db.QueryRow(ctx, usersCreate,
		arg.Name,
		arg.IsAdmin,
		arg.CreatedBy,
		arg.APIToken,
		arg.TelegramID,
		arg.LarkID,
		arg.SlackID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.IsAdmin,
		&i.CreatedBy,
		&i.TelegramID,
		&i.SlackID,
		&i.LarkID,
		&i.APIToken,
	)
	return &i, err
}

const usersDelete = `-- name: UsersDelete :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) UsersDelete(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, usersDelete, id)
	return err
}

const usersGetByAPIToken = `-- name: UsersGetByAPIToken :one
SELECT id, name, created_at, is_admin, created_by, telegram_id, slack_id, lark_id, api_token FROM users WHERE api_token = $1::text
`

func (q *Queries) UsersGetByAPIToken(ctx context.Context, token string) (*User, error) {
	row := q.db.QueryRow(ctx, usersGetByAPIToken, token)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.IsAdmin,
		&i.CreatedBy,
		&i.TelegramID,
		&i.SlackID,
		&i.LarkID,
		&i.APIToken,
	)
	return &i, err
}

const usersGetByID = `-- name: UsersGetByID :one
SELECT id, name, created_at, is_admin, created_by, telegram_id, slack_id, lark_id, api_token FROM users WHERE id = $1
`

func (q *Queries) UsersGetByID(ctx context.Context, id int64) (*User, error) {
	row := q.db.QueryRow(ctx, usersGetByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.IsAdmin,
		&i.CreatedBy,
		&i.TelegramID,
		&i.SlackID,
		&i.LarkID,
		&i.APIToken,
	)
	return &i, err
}

const usersGetByLarkID = `-- name: UsersGetByLarkID :one
SELECT id, name, created_at, is_admin, created_by, telegram_id, slack_id, lark_id, api_token FROM users WHERE lark_id = $1::text
`

func (q *Queries) UsersGetByLarkID(ctx context.Context, id string) (*User, error) {
	row := q.db.QueryRow(ctx, usersGetByLarkID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.IsAdmin,
		&i.CreatedBy,
		&i.TelegramID,
		&i.SlackID,
		&i.LarkID,
		&i.APIToken,
	)
	return &i, err
}

const usersGetByName = `-- name: UsersGetByName :one
SELECT id, name, created_at, is_admin, created_by, telegram_id, slack_id, lark_id, api_token FROM users WHERE name = $1
`

func (q *Queries) UsersGetByName(ctx context.Context, name string) (*User, error) {
	row := q.db.QueryRow(ctx, usersGetByName, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.IsAdmin,
		&i.CreatedBy,
		&i.TelegramID,
		&i.SlackID,
		&i.LarkID,
		&i.APIToken,
	)
	return &i, err
}

const usersGetBySlackID = `-- name: UsersGetBySlackID :one
SELECT id, name, created_at, is_admin, created_by, telegram_id, slack_id, lark_id, api_token FROM users WHERE slack_id = $1::text
`

func (q *Queries) UsersGetBySlackID(ctx context.Context, id string) (*User, error) {
	row := q.db.QueryRow(ctx, usersGetBySlackID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.IsAdmin,
		&i.CreatedBy,
		&i.TelegramID,
		&i.SlackID,
		&i.LarkID,
		&i.APIToken,
	)
	return &i, err
}

const usersGetByTelegramID = `-- name: UsersGetByTelegramID :one
SELECT id, name, created_at, is_admin, created_by, telegram_id, slack_id, lark_id, api_token FROM users WHERE telegram_id = $1::bigint
`

func (q *Queries) UsersGetByTelegramID(ctx context.Context, id int64) (*User, error) {
	row := q.db.QueryRow(ctx, usersGetByTelegramID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.IsAdmin,
		&i.CreatedBy,
		&i.TelegramID,
		&i.SlackID,
		&i.LarkID,
		&i.APIToken,
	)
	return &i, err
}

const usersList = `-- name: UsersList :many
SELECT id, name, created_at, is_admin, created_by, telegram_id, slack_id, lark_id, api_token FROM users
`

func (q *Queries) UsersList(ctx context.Context) ([]*User, error) {
	rows, err := q.db.Query(ctx, usersList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.IsAdmin,
			&i.CreatedBy,
			&i.TelegramID,
			&i.SlackID,
			&i.LarkID,
			&i.APIToken,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usersUpdate = `-- name: UsersUpdate :one
UPDATE users
SET
  name = $2,
  is_admin = $3,
  created_by = $4,
  api_token = $5,
  telegram_id = $6,
  lark_id = $7,
  slack_id = $8
WHERE id = $1
RETURNING id, name, created_at, is_admin, created_by, telegram_id, slack_id, lark_id, api_token
`

type UsersUpdateParams struct {
	ID         int64   `db:"id"`
	Name       string  `db:"name"`
	IsAdmin    bool    `db:"is_admin"`
	CreatedBy  *int64  `db:"created_by"`
	APIToken   *string `db:"api_token"`
	TelegramID *int64  `db:"telegram_id"`
	LarkID     *string `db:"lark_id"`
	SlackID    *string `db:"slack_id"`
}

func (q *Queries) UsersUpdate(ctx context.Context, arg UsersUpdateParams) (*User, error) {
	row := q.db.QueryRow(ctx, usersUpdate,
		arg.ID,
		arg.Name,
		arg.IsAdmin,
		arg.CreatedBy,
		arg.APIToken,
		arg.TelegramID,
		arg.LarkID,
		arg.SlackID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.IsAdmin,
		&i.CreatedBy,
		&i.TelegramID,
		&i.SlackID,
		&i.LarkID,
		&i.APIToken,
	)
	return &i, err
}
