// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
)

const usersDelete = `-- name: UsersDelete :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) UsersDelete(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, usersDelete, id)
	return err
}

const usersGetByID = `-- name: UsersGetByID :one
SELECT id, name, created_at, is_admin, created_by, params FROM users_full WHERE id = $1
`

func (q *Queries) UsersGetByID(ctx context.Context, id int64) (*UsersFull, error) {
	row := q.db.QueryRow(ctx, usersGetByID, id)
	var i UsersFull
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.IsAdmin,
		&i.CreatedBy,
		&i.Params,
	)
	return &i, err
}

const usersGetByName = `-- name: UsersGetByName :one
SELECT id, name, created_at, is_admin, created_by, params FROM users_full WHERE name = $1
`

func (q *Queries) UsersGetByName(ctx context.Context, name string) (*UsersFull, error) {
	row := q.db.QueryRow(ctx, usersGetByName, name)
	var i UsersFull
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.IsAdmin,
		&i.CreatedBy,
		&i.Params,
	)
	return &i, err
}

const usersGetByParam = `-- name: UsersGetByParam :one
SELECT id, name, created_at, is_admin, created_by, params FROM users_full WHERE params->>$1::text = $2::text
`

func (q *Queries) UsersGetByParam(ctx context.Context, key string, value string) (*UsersFull, error) {
	row := q.db.QueryRow(ctx, usersGetByParam, key, value)
	var i UsersFull
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.IsAdmin,
		&i.CreatedBy,
		&i.Params,
	)
	return &i, err
}

const usersList = `-- name: UsersList :many
SELECT id, name, created_at, is_admin, created_by, params FROM users_full
`

func (q *Queries) UsersList(ctx context.Context) ([]*UsersFull, error) {
	rows, err := q.db.Query(ctx, usersList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*UsersFull{}
	for rows.Next() {
		var i UsersFull
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.IsAdmin,
			&i.CreatedBy,
			&i.Params,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userParamsInsert = `-- name: userParamsInsert :exec
INSERT INTO user_params(user_id, key, value)
VALUES ($1, $2, $3)
`

type userParamsInsertParams struct {
	UserID int64  `db:"user_id"`
	Key    string `db:"key"`
	Value  string `db:"value"`
}

func (q *Queries) userParamsInsert(ctx context.Context, arg userParamsInsertParams) error {
	_, err := q.db.Exec(ctx, userParamsInsert, arg.UserID, arg.Key, arg.Value)
	return err
}

const userParamsUpdate = `-- name: userParamsUpdate :exec
UPDATE user_params
SET
  value = $3
WHERE user_id = $1 AND key = $2
`

type userParamsUpdateParams struct {
	UserID int64  `db:"user_id"`
	Key    string `db:"key"`
	Value  string `db:"value"`
}

func (q *Queries) userParamsUpdate(ctx context.Context, arg userParamsUpdateParams) error {
	_, err := q.db.Exec(ctx, userParamsUpdate, arg.UserID, arg.Key, arg.Value)
	return err
}

const usersInsert = `-- name: usersInsert :one
INSERT INTO users (name, is_admin, created_by, created_at)
VALUES ($1, $2, $3, now())
RETURNING id, name, created_at, is_admin, created_by
`

type usersInsertParams struct {
	Name      string `db:"name"`
	IsAdmin   bool   `db:"is_admin"`
	CreatedBy *int64 `db:"created_by"`
}

func (q *Queries) usersInsert(ctx context.Context, arg usersInsertParams) (*User, error) {
	row := q.db.QueryRow(ctx, usersInsert, arg.Name, arg.IsAdmin, arg.CreatedBy)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.IsAdmin,
		&i.CreatedBy,
	)
	return &i, err
}

const usersUpdate = `-- name: usersUpdate :one
UPDATE users
SET
  name = $2,
  is_admin = $3,
  created_by = $4
WHERE id = $1
RETURNING id, name, created_at, is_admin, created_by
`

type usersUpdateParams struct {
	ID        int64  `db:"id"`
	Name      string `db:"name"`
	IsAdmin   bool   `db:"is_admin"`
	CreatedBy *int64 `db:"created_by"`
}

func (q *Queries) usersUpdate(ctx context.Context, arg usersUpdateParams) (*User, error) {
	row := q.db.QueryRow(ctx, usersUpdate,
		arg.ID,
		arg.Name,
		arg.IsAdmin,
		arg.CreatedBy,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.IsAdmin,
		&i.CreatedBy,
	)
	return &i, err
}
