// Code generated by mockery v1.0.0. DO NOT EDIT.

package server_mocks

import (
	net "net"

	mock "github.com/stretchr/testify/mock"
)

// RequestNotifier is an autogenerated mock type for the RequestNotifier type
type RequestNotifier struct {
	mock.Mock
}

// Notify provides a mock function with given fields: _a0, _a1, _a2
func (_m *RequestNotifier) Notify(_a0 net.Addr, _a1 []byte, _a2 map[string]interface{}) {
	_m.Called(_a0, _a1, _a2)
}
