version: 2
project_name: sonar

before:
  hooks:
    - go mod download
    - make completions

builds:
  - id: server
    binary: server
    dir: ./cmd/server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: client
    binary: sonar
    dir: ./cmd/client
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: windows
        goarch: "arm"
      - goos: windows
        goarch: "arm64"

archives:
  - id: client
    ids:
      - client
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - completions/*

homebrew_casks:
  - name: sonar
    ids:
      - client
    repository:
      owner: nt0xa
      name: homebrew-sonar
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Casks
    completions:
      bash: "completions/sonar.bash"
      zsh: "completions/sonar.zsh"
      fish: "completions/sonar.fish"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  disable: true

dockers_v2:
  - images:
      - "ghcr.io/nt0xa/sonar"
    ids:
      - server
    tags:
      - "latest"
      - "{{.Major}}"
      - "{{.Major}}.{{.Minor}}"
      - "{{.Major}}.{{.Minor}}.{{.Patch}}"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
    extra_files:
      - internal/database/migrations
    dockerfile: Dockerfile.ci
    flags:
      - "--pull"
