version: 2
project_name: sonar

before:
  hooks:
    - go mod download

builds:
  - id: server
    binary: server
    dir: ./cmd/server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
  - id: client
    binary: sonar
    dir: ./cmd/client
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: windows
        goarch: 'arm'
      - goos: windows
        goarch: 'arm64'

archives:
  - id: client
    builds:
     - client
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

brews:
  - name: sonar

    ids:
      - client

    repository:
      owner: nt0xa
      name: homebrew-sonar
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
      
    install: |
      bin.install "sonar"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  disable: true

dockers:
- image_templates:
    - "ghcr.io/nt0xa/sonar:latest"
    - "ghcr.io/nt0xa/sonar:{{.Major}}"
    - "ghcr.io/nt0xa/sonar:{{.Major}}.{{.Minor}}"
    - "ghcr.io/nt0xa/sonar:{{.Major}}.{{.Minor}}.{{.Patch}}"
  build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
  extra_files:
    - internal/database/migrations
  dockerfile: Dockerfile.ci
