project_name: sonar

before:
  hooks:
    - go mod download

builds:
  - id: server
    binary: server
    dir: ./cmd/server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
  - id: client
    binary: sonar
    dir: ./cmd/client
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: windows
        goarch: 'arm'
      - goos: windows
        goarch: 'arm64'

archives:
  - id: client
    builds:
     - client
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64

brews:
  - name: sonar

    ids:
    - client

    tap:
      owner: russtone
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
      
    install: |
      bin.install "sonar"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  skip: true

dockers:
- image_templates:
    - "ghcr.io/russtone/sonar:latest"
    - "ghcr.io/russtone/sonar:{{.Major}}"
    - "ghcr.io/russtone/sonar:{{.Major}}.{{.Minor}}"
    - "ghcr.io/russtone/sonar:{{.Major}}.{{.Minor}}.{{.Patch}}"
  build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
  extra_files:
    - internal/database/migrations
  dockerfile: Dockerfile.ci
