// Code generated by mockery v2.53.6. DO NOT EDIT.

package service_mock

import (
	context "context"

	service "github.com/nt0xa/sonar/internal/service"
	mock "github.com/stretchr/testify/mock"
)

// ServerService is an autogenerated mock type for the ServerService type
type ServerService struct {
	mock.Mock
}

// AuditRecordsGet provides a mock function with given fields: _a0, _a1
func (_m *ServerService) AuditRecordsGet(_a0 context.Context, _a1 service.AuditRecordsGetInput) (*service.AuditRecord, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AuditRecordsGet")
	}

	var r0 *service.AuditRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.AuditRecordsGetInput) (*service.AuditRecord, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.AuditRecordsGetInput) *service.AuditRecord); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.AuditRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.AuditRecordsGetInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuditRecordsList provides a mock function with given fields: _a0, _a1
func (_m *ServerService) AuditRecordsList(_a0 context.Context, _a1 service.AuditRecordsListInput) ([]service.AuditRecord, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AuditRecordsList")
	}

	var r0 []service.AuditRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.AuditRecordsListInput) ([]service.AuditRecord, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.AuditRecordsListInput) []service.AuditRecord); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.AuditRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.AuditRecordsListInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthContextByAPIToken provides a mock function with given fields: _a0, _a1
func (_m *ServerService) AuthContextByAPIToken(_a0 context.Context, _a1 string) (context.Context, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AuthContextByAPIToken")
	}

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (context.Context, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) context.Context); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthContextByLarkID provides a mock function with given fields: _a0, _a1
func (_m *ServerService) AuthContextByLarkID(_a0 context.Context, _a1 string) (context.Context, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AuthContextByLarkID")
	}

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (context.Context, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) context.Context); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthContextBySlackID provides a mock function with given fields: _a0, _a1
func (_m *ServerService) AuthContextBySlackID(_a0 context.Context, _a1 string) (context.Context, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AuthContextBySlackID")
	}

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (context.Context, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) context.Context); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthContextByTelegramID provides a mock function with given fields: _a0, _a1
func (_m *ServerService) AuthContextByTelegramID(_a0 context.Context, _a1 int64) (context.Context, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AuthContextByTelegramID")
	}

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (context.Context, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) context.Context); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DNSRecordsClear provides a mock function with given fields: _a0, _a1
func (_m *ServerService) DNSRecordsClear(_a0 context.Context, _a1 service.DNSRecordsClearInput) ([]service.DNSRecord, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DNSRecordsClear")
	}

	var r0 []service.DNSRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.DNSRecordsClearInput) ([]service.DNSRecord, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.DNSRecordsClearInput) []service.DNSRecord); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.DNSRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.DNSRecordsClearInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DNSRecordsCreate provides a mock function with given fields: _a0, _a1
func (_m *ServerService) DNSRecordsCreate(_a0 context.Context, _a1 service.DNSRecordsCreateInput) (*service.DNSRecord, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DNSRecordsCreate")
	}

	var r0 *service.DNSRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.DNSRecordsCreateInput) (*service.DNSRecord, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.DNSRecordsCreateInput) *service.DNSRecord); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.DNSRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.DNSRecordsCreateInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DNSRecordsDelete provides a mock function with given fields: _a0, _a1
func (_m *ServerService) DNSRecordsDelete(_a0 context.Context, _a1 service.DNSRecordsDeleteInput) (*service.DNSRecord, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DNSRecordsDelete")
	}

	var r0 *service.DNSRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.DNSRecordsDeleteInput) (*service.DNSRecord, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.DNSRecordsDeleteInput) *service.DNSRecord); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.DNSRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.DNSRecordsDeleteInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DNSRecordsList provides a mock function with given fields: _a0, _a1
func (_m *ServerService) DNSRecordsList(_a0 context.Context, _a1 service.DNSRecordsListInput) ([]service.DNSRecord, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DNSRecordsList")
	}

	var r0 []service.DNSRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.DNSRecordsListInput) ([]service.DNSRecord, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.DNSRecordsListInput) []service.DNSRecord); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.DNSRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.DNSRecordsListInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventsGet provides a mock function with given fields: _a0, _a1
func (_m *ServerService) EventsGet(_a0 context.Context, _a1 service.EventsGetInput) (*service.Event, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for EventsGet")
	}

	var r0 *service.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.EventsGetInput) (*service.Event, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.EventsGetInput) *service.Event); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.EventsGetInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventsList provides a mock function with given fields: _a0, _a1
func (_m *ServerService) EventsList(_a0 context.Context, _a1 service.EventsListInput) ([]service.Event, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for EventsList")
	}

	var r0 []service.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.EventsListInput) ([]service.Event, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.EventsListInput) []service.Event); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.EventsListInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HTTPRoutesClear provides a mock function with given fields: _a0, _a1
func (_m *ServerService) HTTPRoutesClear(_a0 context.Context, _a1 service.HTTPRoutesClearInput) ([]service.HTTPRoute, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for HTTPRoutesClear")
	}

	var r0 []service.HTTPRoute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.HTTPRoutesClearInput) ([]service.HTTPRoute, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.HTTPRoutesClearInput) []service.HTTPRoute); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.HTTPRoute)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.HTTPRoutesClearInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HTTPRoutesCreate provides a mock function with given fields: _a0, _a1
func (_m *ServerService) HTTPRoutesCreate(_a0 context.Context, _a1 service.HTTPRoutesCreateInput) (*service.HTTPRoute, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for HTTPRoutesCreate")
	}

	var r0 *service.HTTPRoute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.HTTPRoutesCreateInput) (*service.HTTPRoute, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.HTTPRoutesCreateInput) *service.HTTPRoute); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.HTTPRoute)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.HTTPRoutesCreateInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HTTPRoutesDelete provides a mock function with given fields: _a0, _a1
func (_m *ServerService) HTTPRoutesDelete(_a0 context.Context, _a1 service.HTTPRoutesDeleteInput) (*service.HTTPRoute, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for HTTPRoutesDelete")
	}

	var r0 *service.HTTPRoute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.HTTPRoutesDeleteInput) (*service.HTTPRoute, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.HTTPRoutesDeleteInput) *service.HTTPRoute); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.HTTPRoute)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.HTTPRoutesDeleteInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HTTPRoutesList provides a mock function with given fields: _a0, _a1
func (_m *ServerService) HTTPRoutesList(_a0 context.Context, _a1 service.HTTPRoutesListInput) ([]service.HTTPRoute, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for HTTPRoutesList")
	}

	var r0 []service.HTTPRoute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.HTTPRoutesListInput) ([]service.HTTPRoute, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.HTTPRoutesListInput) []service.HTTPRoute); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.HTTPRoute)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.HTTPRoutesListInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HTTPRoutesUpdate provides a mock function with given fields: _a0, _a1
func (_m *ServerService) HTTPRoutesUpdate(_a0 context.Context, _a1 service.HTTPRoutesUpdateInput) (*service.HTTPRoute, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for HTTPRoutesUpdate")
	}

	var r0 *service.HTTPRoute
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.HTTPRoutesUpdateInput) (*service.HTTPRoute, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.HTTPRoutesUpdateInput) *service.HTTPRoute); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.HTTPRoute)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.HTTPRoutesUpdateInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PayloadsClear provides a mock function with given fields: _a0, _a1
func (_m *ServerService) PayloadsClear(_a0 context.Context, _a1 service.PayloadsClearInput) ([]service.Payload, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PayloadsClear")
	}

	var r0 []service.Payload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.PayloadsClearInput) ([]service.Payload, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.PayloadsClearInput) []service.Payload); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.Payload)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.PayloadsClearInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PayloadsCreate provides a mock function with given fields: _a0, _a1
func (_m *ServerService) PayloadsCreate(_a0 context.Context, _a1 service.PayloadsCreateInput) (*service.Payload, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PayloadsCreate")
	}

	var r0 *service.Payload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.PayloadsCreateInput) (*service.Payload, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.PayloadsCreateInput) *service.Payload); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Payload)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.PayloadsCreateInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PayloadsDelete provides a mock function with given fields: _a0, _a1
func (_m *ServerService) PayloadsDelete(_a0 context.Context, _a1 service.PayloadsDeleteInput) (*service.Payload, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PayloadsDelete")
	}

	var r0 *service.Payload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.PayloadsDeleteInput) (*service.Payload, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.PayloadsDeleteInput) *service.Payload); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Payload)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.PayloadsDeleteInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PayloadsList provides a mock function with given fields: _a0, _a1
func (_m *ServerService) PayloadsList(_a0 context.Context, _a1 service.PayloadsListInput) ([]service.Payload, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PayloadsList")
	}

	var r0 []service.Payload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.PayloadsListInput) ([]service.Payload, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.PayloadsListInput) []service.Payload); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.Payload)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.PayloadsListInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PayloadsUpdate provides a mock function with given fields: _a0, _a1
func (_m *ServerService) PayloadsUpdate(_a0 context.Context, _a1 service.PayloadsUpdateInput) (*service.Payload, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PayloadsUpdate")
	}

	var r0 *service.Payload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.PayloadsUpdateInput) (*service.Payload, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.PayloadsUpdateInput) *service.Payload); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Payload)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.PayloadsUpdateInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProfileGet provides a mock function with given fields: _a0
func (_m *ServerService) ProfileGet(_a0 context.Context) (*service.User, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ProfileGet")
	}

	var r0 *service.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*service.User, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *service.User); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsersCreate provides a mock function with given fields: _a0, _a1
func (_m *ServerService) UsersCreate(_a0 context.Context, _a1 service.UsersCreateInput) (*service.User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UsersCreate")
	}

	var r0 *service.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.UsersCreateInput) (*service.User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.UsersCreateInput) *service.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.UsersCreateInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsersDelete provides a mock function with given fields: _a0, _a1
func (_m *ServerService) UsersDelete(_a0 context.Context, _a1 service.UsersDeleteInput) (*service.User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UsersDelete")
	}

	var r0 *service.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.UsersDeleteInput) (*service.User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.UsersDeleteInput) *service.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.UsersDeleteInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewServerService creates a new instance of ServerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServerService {
	mock := &ServerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
