// Code generated by mockery v2.53.6. DO NOT EDIT.

package service_mock

import (
	context "context"

	service "github.com/nt0xa/sonar/internal/service"
	mock "github.com/stretchr/testify/mock"
)

// ServerService is an autogenerated mock type for the ServerService type
type ServerService struct {
	mock.Mock
}

// AuditRecordsGet provides a mock function with given fields: _a0, _a1
func (_m *ServerService) AuditRecordsGet(_a0 context.Context, _a1 service.AuditRecordsGetInput) (*service.AuditRecordsGetOutput, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AuditRecordsGet")
	}

	var r0 *service.AuditRecordsGetOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.AuditRecordsGetInput) (*service.AuditRecordsGetOutput, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.AuditRecordsGetInput) *service.AuditRecordsGetOutput); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.AuditRecordsGetOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.AuditRecordsGetInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuditRecordsList provides a mock function with given fields: _a0, _a1
func (_m *ServerService) AuditRecordsList(_a0 context.Context, _a1 service.AuditRecordsListInput) (service.AuditRecordsListOutput, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AuditRecordsList")
	}

	var r0 service.AuditRecordsListOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.AuditRecordsListInput) (service.AuditRecordsListOutput, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.AuditRecordsListInput) service.AuditRecordsListOutput); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.AuditRecordsListOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.AuditRecordsListInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthContextByAPIToken provides a mock function with given fields: _a0, _a1
func (_m *ServerService) AuthContextByAPIToken(_a0 context.Context, _a1 string) (context.Context, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AuthContextByAPIToken")
	}

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (context.Context, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) context.Context); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthContextByLarkID provides a mock function with given fields: _a0, _a1
func (_m *ServerService) AuthContextByLarkID(_a0 context.Context, _a1 string) (context.Context, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AuthContextByLarkID")
	}

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (context.Context, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) context.Context); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthContextBySlackID provides a mock function with given fields: _a0, _a1
func (_m *ServerService) AuthContextBySlackID(_a0 context.Context, _a1 string) (context.Context, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AuthContextBySlackID")
	}

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (context.Context, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) context.Context); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthContextByTelegramID provides a mock function with given fields: _a0, _a1
func (_m *ServerService) AuthContextByTelegramID(_a0 context.Context, _a1 int64) (context.Context, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AuthContextByTelegramID")
	}

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (context.Context, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) context.Context); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DNSRecordsClear provides a mock function with given fields: _a0, _a1
func (_m *ServerService) DNSRecordsClear(_a0 context.Context, _a1 service.DNSRecordsClearInput) (service.DNSRecordsClearOutput, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DNSRecordsClear")
	}

	var r0 service.DNSRecordsClearOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.DNSRecordsClearInput) (service.DNSRecordsClearOutput, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.DNSRecordsClearInput) service.DNSRecordsClearOutput); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.DNSRecordsClearOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.DNSRecordsClearInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DNSRecordsCreate provides a mock function with given fields: _a0, _a1
func (_m *ServerService) DNSRecordsCreate(_a0 context.Context, _a1 service.DNSRecordsCreateInput) (*service.DNSRecordsCreateOutput, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DNSRecordsCreate")
	}

	var r0 *service.DNSRecordsCreateOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.DNSRecordsCreateInput) (*service.DNSRecordsCreateOutput, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.DNSRecordsCreateInput) *service.DNSRecordsCreateOutput); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.DNSRecordsCreateOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.DNSRecordsCreateInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DNSRecordsDelete provides a mock function with given fields: _a0, _a1
func (_m *ServerService) DNSRecordsDelete(_a0 context.Context, _a1 service.DNSRecordsDeleteInput) (*service.DNSRecordsDeleteOutput, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DNSRecordsDelete")
	}

	var r0 *service.DNSRecordsDeleteOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.DNSRecordsDeleteInput) (*service.DNSRecordsDeleteOutput, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.DNSRecordsDeleteInput) *service.DNSRecordsDeleteOutput); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.DNSRecordsDeleteOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.DNSRecordsDeleteInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DNSRecordsList provides a mock function with given fields: _a0, _a1
func (_m *ServerService) DNSRecordsList(_a0 context.Context, _a1 service.DNSRecordsListInput) (service.DNSRecordsListOutput, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DNSRecordsList")
	}

	var r0 service.DNSRecordsListOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.DNSRecordsListInput) (service.DNSRecordsListOutput, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.DNSRecordsListInput) service.DNSRecordsListOutput); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.DNSRecordsListOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.DNSRecordsListInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventsGet provides a mock function with given fields: _a0, _a1
func (_m *ServerService) EventsGet(_a0 context.Context, _a1 service.EventsGetInput) (*service.EventsGetOutput, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for EventsGet")
	}

	var r0 *service.EventsGetOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.EventsGetInput) (*service.EventsGetOutput, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.EventsGetInput) *service.EventsGetOutput); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.EventsGetOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.EventsGetInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EventsList provides a mock function with given fields: _a0, _a1
func (_m *ServerService) EventsList(_a0 context.Context, _a1 service.EventsListInput) (service.EventsListOutput, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for EventsList")
	}

	var r0 service.EventsListOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.EventsListInput) (service.EventsListOutput, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.EventsListInput) service.EventsListOutput); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.EventsListOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.EventsListInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HTTPRoutesClear provides a mock function with given fields: _a0, _a1
func (_m *ServerService) HTTPRoutesClear(_a0 context.Context, _a1 service.HTTPRoutesClearInput) (service.HTTPRoutesClearOutput, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for HTTPRoutesClear")
	}

	var r0 service.HTTPRoutesClearOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.HTTPRoutesClearInput) (service.HTTPRoutesClearOutput, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.HTTPRoutesClearInput) service.HTTPRoutesClearOutput); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.HTTPRoutesClearOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.HTTPRoutesClearInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HTTPRoutesCreate provides a mock function with given fields: _a0, _a1
func (_m *ServerService) HTTPRoutesCreate(_a0 context.Context, _a1 service.HTTPRoutesCreateInput) (*service.HTTPRoutesCreateOutput, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for HTTPRoutesCreate")
	}

	var r0 *service.HTTPRoutesCreateOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.HTTPRoutesCreateInput) (*service.HTTPRoutesCreateOutput, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.HTTPRoutesCreateInput) *service.HTTPRoutesCreateOutput); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.HTTPRoutesCreateOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.HTTPRoutesCreateInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HTTPRoutesDelete provides a mock function with given fields: _a0, _a1
func (_m *ServerService) HTTPRoutesDelete(_a0 context.Context, _a1 service.HTTPRoutesDeleteInput) (*service.HTTPRoutesDeleteOutput, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for HTTPRoutesDelete")
	}

	var r0 *service.HTTPRoutesDeleteOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.HTTPRoutesDeleteInput) (*service.HTTPRoutesDeleteOutput, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.HTTPRoutesDeleteInput) *service.HTTPRoutesDeleteOutput); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.HTTPRoutesDeleteOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.HTTPRoutesDeleteInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HTTPRoutesList provides a mock function with given fields: _a0, _a1
func (_m *ServerService) HTTPRoutesList(_a0 context.Context, _a1 service.HTTPRoutesListInput) (service.HTTPRoutesListOutput, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for HTTPRoutesList")
	}

	var r0 service.HTTPRoutesListOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.HTTPRoutesListInput) (service.HTTPRoutesListOutput, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.HTTPRoutesListInput) service.HTTPRoutesListOutput); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.HTTPRoutesListOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.HTTPRoutesListInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HTTPRoutesUpdate provides a mock function with given fields: _a0, _a1
func (_m *ServerService) HTTPRoutesUpdate(_a0 context.Context, _a1 service.HTTPRoutesUpdateInput) (*service.HTTPRoutesUpdateOutput, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for HTTPRoutesUpdate")
	}

	var r0 *service.HTTPRoutesUpdateOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.HTTPRoutesUpdateInput) (*service.HTTPRoutesUpdateOutput, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.HTTPRoutesUpdateInput) *service.HTTPRoutesUpdateOutput); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.HTTPRoutesUpdateOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.HTTPRoutesUpdateInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LarkProvisionUser provides a mock function with given fields: _a0, _a1
func (_m *ServerService) LarkProvisionUser(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for LarkProvisionUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PayloadsClear provides a mock function with given fields: _a0, _a1
func (_m *ServerService) PayloadsClear(_a0 context.Context, _a1 service.PayloadsClearInput) (service.PayloadsClearOutput, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PayloadsClear")
	}

	var r0 service.PayloadsClearOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.PayloadsClearInput) (service.PayloadsClearOutput, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.PayloadsClearInput) service.PayloadsClearOutput); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.PayloadsClearOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.PayloadsClearInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PayloadsCreate provides a mock function with given fields: _a0, _a1
func (_m *ServerService) PayloadsCreate(_a0 context.Context, _a1 service.PayloadsCreateInput) (*service.PayloadsCreateOutput, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PayloadsCreate")
	}

	var r0 *service.PayloadsCreateOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.PayloadsCreateInput) (*service.PayloadsCreateOutput, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.PayloadsCreateInput) *service.PayloadsCreateOutput); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.PayloadsCreateOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.PayloadsCreateInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PayloadsDelete provides a mock function with given fields: _a0, _a1
func (_m *ServerService) PayloadsDelete(_a0 context.Context, _a1 service.PayloadsDeleteInput) (*service.PayloadsDeleteOutput, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PayloadsDelete")
	}

	var r0 *service.PayloadsDeleteOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.PayloadsDeleteInput) (*service.PayloadsDeleteOutput, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.PayloadsDeleteInput) *service.PayloadsDeleteOutput); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.PayloadsDeleteOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.PayloadsDeleteInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PayloadsList provides a mock function with given fields: _a0, _a1
func (_m *ServerService) PayloadsList(_a0 context.Context, _a1 service.PayloadsListInput) (service.PayloadsListOutput, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PayloadsList")
	}

	var r0 service.PayloadsListOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.PayloadsListInput) (service.PayloadsListOutput, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.PayloadsListInput) service.PayloadsListOutput); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.PayloadsListOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.PayloadsListInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PayloadsUpdate provides a mock function with given fields: _a0, _a1
func (_m *ServerService) PayloadsUpdate(_a0 context.Context, _a1 service.PayloadsUpdateInput) (*service.PayloadsUpdateOutput, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PayloadsUpdate")
	}

	var r0 *service.PayloadsUpdateOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.PayloadsUpdateInput) (*service.PayloadsUpdateOutput, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.PayloadsUpdateInput) *service.PayloadsUpdateOutput); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.PayloadsUpdateOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.PayloadsUpdateInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProfileGet provides a mock function with given fields: _a0
func (_m *ServerService) ProfileGet(_a0 context.Context) (*service.ProfileGetOutput, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ProfileGet")
	}

	var r0 *service.ProfileGetOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*service.ProfileGetOutput, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *service.ProfileGetOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.ProfileGetOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsersCreate provides a mock function with given fields: _a0, _a1
func (_m *ServerService) UsersCreate(_a0 context.Context, _a1 service.UsersCreateInput) (*service.UsersCreateOutput, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UsersCreate")
	}

	var r0 *service.UsersCreateOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.UsersCreateInput) (*service.UsersCreateOutput, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.UsersCreateInput) *service.UsersCreateOutput); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.UsersCreateOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.UsersCreateInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsersDelete provides a mock function with given fields: _a0, _a1
func (_m *ServerService) UsersDelete(_a0 context.Context, _a1 service.UsersDeleteInput) (*service.UsersDeleteOutput, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UsersDelete")
	}

	var r0 *service.UsersDeleteOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.UsersDeleteInput) (*service.UsersDeleteOutput, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.UsersDeleteInput) *service.UsersDeleteOutput); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.UsersDeleteOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.UsersDeleteInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewServerService creates a new instance of ServerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServerService {
	mock := &ServerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
