package cmd3

import (
	"strings"

	"github.com/spf13/pflag"

	"github.com/nt0xa/sonar/internal/service"
)

// The single-value enum fields satisfy pflag.Value directly via the
// String/Set/Type methods generated by go-enum's --flag option, so they bind to
// cobra's VarP without any hand-written bridge. These assertions document that
// dependency — drop --flag and they stop compiling.
var (
	_ pflag.Value = (*service.DNSRecordType)(nil)
	_ pflag.Value = (*service.DNSRecordStrategy)(nil)
	_ pflag.Value = (*service.HTTPMethod)(nil)
	_ pflag.Value = (*service.AuditResourceType)(nil)
	_ pflag.Value = (*service.AuditAction)(nil)
	_ pflag.Value = (*protoSlice)(nil)
)

// protoSlice binds a []ProtoCategory flag. Mirrors pflag's stringSlice: the first
// Set replaces, later occurrences append; a single value may be comma-separated.
// go-enum's --flag only covers single values, so this slice flag stays hand-written.
type protoSlice struct {
	p       *[]service.ProtoCategory
	changed bool
}

func (v *protoSlice) Type() string { return "strings" }

func (v *protoSlice) String() string {
	if v.p == nil || len(*v.p) == 0 {
		return ""
	}
	parts := make([]string, len(*v.p))
	for i, c := range *v.p {
		parts[i] = string(c)
	}
	return "[" + strings.Join(parts, ",") + "]"
}

func (v *protoSlice) Set(s string) error {
	parts := strings.Split(s, ",")
	out := make([]service.ProtoCategory, 0, len(parts))
	for _, p := range parts {
		c, err := service.ParseProtoCategory(strings.TrimSpace(p))
		if err != nil {
			return err
		}
		out = append(out, c)
	}
	if !v.changed {
		*v.p = out
		v.changed = true
	} else {
		*v.p = append(*v.p, out...)
	}
	return nil
}
