// Code generated by mockery v2.23.0. DO NOT EDIT.

package actions_mock

import (
	context "context"

	actions "github.com/russtone/sonar/internal/actions"

	mock "github.com/stretchr/testify/mock"
)

// ResultHandler is an autogenerated mock type for the ResultHandler type
type ResultHandler struct {
	mock.Mock
}

// OnResult provides a mock function with given fields: _a0, _a1
func (_m *ResultHandler) OnResult(_a0 context.Context, _a1 actions.Result) {
	_m.Called(_a0, _a1)
}

type mockConstructorTestingTNewResultHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewResultHandler creates a new instance of ResultHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewResultHandler(t mockConstructorTestingTNewResultHandler) *ResultHandler {
	mock := &ResultHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
