// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: http_routes.sql

package database2

import (
	"context"
)

const hTTPRoutesCreate = `-- name: HTTPRoutesCreate :one
INSERT INTO http_routes (payload_id, method, path, code, headers, body,
  is_dynamic, created_at, index)
VALUES ($1, $2, $3, $4, $5, $6, $7, now(),
  (SELECT COALESCE(MAX(index), 0) FROM http_routes hr WHERE hr.payload_id = $1) + 1)
RETURNING id, payload_id, method, path, code, headers, body, is_dynamic, created_at, index
`

type HTTPRoutesCreateParams struct {
	PayloadID int64       `db:"payload_id"`
	Method    string      `db:"method"`
	Path      string      `db:"path"`
	Code      int32       `db:"code"`
	Headers   HTTPHeaders `db:"headers"`
	Body      []byte      `db:"body"`
	IsDynamic bool        `db:"is_dynamic"`
}

func (q *Queries) HTTPRoutesCreate(ctx context.Context, arg HTTPRoutesCreateParams) (*HTTPRoute, error) {
	row := q.db.QueryRow(ctx, hTTPRoutesCreate,
		arg.PayloadID,
		arg.Method,
		arg.Path,
		arg.Code,
		arg.Headers,
		arg.Body,
		arg.IsDynamic,
	)
	var i HTTPRoute
	err := row.Scan(
		&i.ID,
		&i.PayloadID,
		&i.Method,
		&i.Path,
		&i.Code,
		&i.Headers,
		&i.Body,
		&i.IsDynamic,
		&i.CreatedAt,
		&i.Index,
	)
	return &i, err
}

const hTTPRoutesDelete = `-- name: HTTPRoutesDelete :exec
DELETE FROM http_routes WHERE id = $1
`

func (q *Queries) HTTPRoutesDelete(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, hTTPRoutesDelete, id)
	return err
}

const hTTPRoutesDeleteAllByPayloadID = `-- name: HTTPRoutesDeleteAllByPayloadID :many
DELETE FROM http_routes WHERE payload_id = $1 RETURNING id, payload_id, method, path, code, headers, body, is_dynamic, created_at, index
`

func (q *Queries) HTTPRoutesDeleteAllByPayloadID(ctx context.Context, payloadID int64) ([]*HTTPRoute, error) {
	rows, err := q.db.Query(ctx, hTTPRoutesDeleteAllByPayloadID, payloadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*HTTPRoute{}
	for rows.Next() {
		var i HTTPRoute
		if err := rows.Scan(
			&i.ID,
			&i.PayloadID,
			&i.Method,
			&i.Path,
			&i.Code,
			&i.Headers,
			&i.Body,
			&i.IsDynamic,
			&i.CreatedAt,
			&i.Index,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hTTPRoutesDeleteAllByPayloadIDAndPath = `-- name: HTTPRoutesDeleteAllByPayloadIDAndPath :many
DELETE FROM http_routes WHERE payload_id = $1 AND path = $2 RETURNING id, payload_id, method, path, code, headers, body, is_dynamic, created_at, index
`

func (q *Queries) HTTPRoutesDeleteAllByPayloadIDAndPath(ctx context.Context, payloadID int64, path string) ([]*HTTPRoute, error) {
	rows, err := q.db.Query(ctx, hTTPRoutesDeleteAllByPayloadIDAndPath, payloadID, path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*HTTPRoute{}
	for rows.Next() {
		var i HTTPRoute
		if err := rows.Scan(
			&i.ID,
			&i.PayloadID,
			&i.Method,
			&i.Path,
			&i.Code,
			&i.Headers,
			&i.Body,
			&i.IsDynamic,
			&i.CreatedAt,
			&i.Index,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hTTPRoutesGetByID = `-- name: HTTPRoutesGetByID :one
SELECT id, payload_id, method, path, code, headers, body, is_dynamic, created_at, index FROM http_routes WHERE id = $1
`

func (q *Queries) HTTPRoutesGetByID(ctx context.Context, id int64) (*HTTPRoute, error) {
	row := q.db.QueryRow(ctx, hTTPRoutesGetByID, id)
	var i HTTPRoute
	err := row.Scan(
		&i.ID,
		&i.PayloadID,
		&i.Method,
		&i.Path,
		&i.Code,
		&i.Headers,
		&i.Body,
		&i.IsDynamic,
		&i.CreatedAt,
		&i.Index,
	)
	return &i, err
}

const hTTPRoutesGetByPayloadID = `-- name: HTTPRoutesGetByPayloadID :many
SELECT id, payload_id, method, path, code, headers, body, is_dynamic, created_at, index FROM http_routes WHERE payload_id = $1
`

func (q *Queries) HTTPRoutesGetByPayloadID(ctx context.Context, payloadID int64) ([]*HTTPRoute, error) {
	rows, err := q.db.Query(ctx, hTTPRoutesGetByPayloadID, payloadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*HTTPRoute{}
	for rows.Next() {
		var i HTTPRoute
		if err := rows.Scan(
			&i.ID,
			&i.PayloadID,
			&i.Method,
			&i.Path,
			&i.Code,
			&i.Headers,
			&i.Body,
			&i.IsDynamic,
			&i.CreatedAt,
			&i.Index,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hTTPRoutesGetByPayloadIDAndIndex = `-- name: HTTPRoutesGetByPayloadIDAndIndex :one
SELECT id, payload_id, method, path, code, headers, body, is_dynamic, created_at, index FROM http_routes WHERE payload_id = $1 AND index = $2
`

func (q *Queries) HTTPRoutesGetByPayloadIDAndIndex(ctx context.Context, payloadID int64, index int32) (*HTTPRoute, error) {
	row := q.db.QueryRow(ctx, hTTPRoutesGetByPayloadIDAndIndex, payloadID, index)
	var i HTTPRoute
	err := row.Scan(
		&i.ID,
		&i.PayloadID,
		&i.Method,
		&i.Path,
		&i.Code,
		&i.Headers,
		&i.Body,
		&i.IsDynamic,
		&i.CreatedAt,
		&i.Index,
	)
	return &i, err
}

const hTTPRoutesGetByPayloadMethodAndPath = `-- name: HTTPRoutesGetByPayloadMethodAndPath :one
SELECT id, payload_id, method, path, code, headers, body, is_dynamic, created_at, index FROM http_routes
WHERE payload_id = $1 AND method = $2 AND path = $3
`

type HTTPRoutesGetByPayloadMethodAndPathParams struct {
	PayloadID int64  `db:"payload_id"`
	Method    string `db:"method"`
	Path      string `db:"path"`
}

func (q *Queries) HTTPRoutesGetByPayloadMethodAndPath(ctx context.Context, arg HTTPRoutesGetByPayloadMethodAndPathParams) (*HTTPRoute, error) {
	row := q.db.QueryRow(ctx, hTTPRoutesGetByPayloadMethodAndPath, arg.PayloadID, arg.Method, arg.Path)
	var i HTTPRoute
	err := row.Scan(
		&i.ID,
		&i.PayloadID,
		&i.Method,
		&i.Path,
		&i.Code,
		&i.Headers,
		&i.Body,
		&i.IsDynamic,
		&i.CreatedAt,
		&i.Index,
	)
	return &i, err
}

const hTTPRoutesUpdate = `-- name: HTTPRoutesUpdate :one
UPDATE http_routes SET
  payload_id = $2,
  method = $3,
  path = $4,
  code = $5,
  headers = $6,
  body = $7,
  is_dynamic = $8
WHERE id = $1
RETURNING id, payload_id, method, path, code, headers, body, is_dynamic, created_at, index
`

type HTTPRoutesUpdateParams struct {
	ID        int64       `db:"id"`
	PayloadID int64       `db:"payload_id"`
	Method    string      `db:"method"`
	Path      string      `db:"path"`
	Code      int32       `db:"code"`
	Headers   HTTPHeaders `db:"headers"`
	Body      []byte      `db:"body"`
	IsDynamic bool        `db:"is_dynamic"`
}

func (q *Queries) HTTPRoutesUpdate(ctx context.Context, arg HTTPRoutesUpdateParams) (*HTTPRoute, error) {
	row := q.db.QueryRow(ctx, hTTPRoutesUpdate,
		arg.ID,
		arg.PayloadID,
		arg.Method,
		arg.Path,
		arg.Code,
		arg.Headers,
		arg.Body,
		arg.IsDynamic,
	)
	var i HTTPRoute
	err := row.Scan(
		&i.ID,
		&i.PayloadID,
		&i.Method,
		&i.Path,
		&i.Code,
		&i.Headers,
		&i.Body,
		&i.IsDynamic,
		&i.CreatedAt,
		&i.Index,
	)
	return &i, err
}
