// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database2

import (
	"context"
)

type Querier interface {
	UsersDelete(ctx context.Context, id int64) error
	UsersGetByID(ctx context.Context, id int64) (*UsersFull, error)
	UsersGetByName(ctx context.Context, name string) (*UsersFull, error)
	UsersGetByParam(ctx context.Context, key string, value string) (*UsersFull, error)
	UsersList(ctx context.Context) ([]*UsersFull, error)
	userParamsInsert(ctx context.Context, arg userParamsInsertParams) error
	userParamsUpdate(ctx context.Context, arg userParamsUpdateParams) error
	usersInsert(ctx context.Context, arg usersInsertParams) (*User, error)
	usersUpdate(ctx context.Context, arg usersUpdateParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
