// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package service

import (
	"fmt"
	"strings"
)

const (
	// AuditActionCreate is a AuditAction of type create.
	AuditActionCreate AuditAction = "create"
	// AuditActionUpdate is a AuditAction of type update.
	AuditActionUpdate AuditAction = "update"
	// AuditActionDelete is a AuditAction of type delete.
	AuditActionDelete AuditAction = "delete"
)

var ErrInvalidAuditAction = fmt.Errorf("not a valid AuditAction, try [%s]", strings.Join(_AuditActionNames, ", "))

var _AuditActionNames = []string{
	string(AuditActionCreate),
	string(AuditActionUpdate),
	string(AuditActionDelete),
}

// AuditActionNames returns a list of possible string values of AuditAction.
func AuditActionNames() []string {
	tmp := make([]string, len(_AuditActionNames))
	copy(tmp, _AuditActionNames)
	return tmp
}

// AuditActionValues returns a list of the values for AuditAction
func AuditActionValues() []AuditAction {
	return []AuditAction{
		AuditActionCreate,
		AuditActionUpdate,
		AuditActionDelete,
	}
}

// String implements the Stringer interface.
func (x AuditAction) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x AuditAction) IsValid() bool {
	_, err := ParseAuditAction(string(x))
	return err == nil
}

var _AuditActionValue = map[string]AuditAction{
	"create": AuditActionCreate,
	"update": AuditActionUpdate,
	"delete": AuditActionDelete,
}

// ParseAuditAction attempts to convert a string to a AuditAction.
func ParseAuditAction(name string) (AuditAction, error) {
	if x, ok := _AuditActionValue[name]; ok {
		return x, nil
	}
	return AuditAction(""), fmt.Errorf("%s is %w", name, ErrInvalidAuditAction)
}

func (x AuditAction) Ptr() *AuditAction {
	return &x
}

const (
	// AuditResourceTypePayload is a AuditResourceType of type payload.
	AuditResourceTypePayload AuditResourceType = "payload"
	// AuditResourceTypeUser is a AuditResourceType of type user.
	AuditResourceTypeUser AuditResourceType = "user"
	// AuditResourceTypeDnsRecord is a AuditResourceType of type dns_record.
	AuditResourceTypeDnsRecord AuditResourceType = "dns_record"
	// AuditResourceTypeHttpRoute is a AuditResourceType of type http_route.
	AuditResourceTypeHttpRoute AuditResourceType = "http_route"
)

var ErrInvalidAuditResourceType = fmt.Errorf("not a valid AuditResourceType, try [%s]", strings.Join(_AuditResourceTypeNames, ", "))

var _AuditResourceTypeNames = []string{
	string(AuditResourceTypePayload),
	string(AuditResourceTypeUser),
	string(AuditResourceTypeDnsRecord),
	string(AuditResourceTypeHttpRoute),
}

// AuditResourceTypeNames returns a list of possible string values of AuditResourceType.
func AuditResourceTypeNames() []string {
	tmp := make([]string, len(_AuditResourceTypeNames))
	copy(tmp, _AuditResourceTypeNames)
	return tmp
}

// AuditResourceTypeValues returns a list of the values for AuditResourceType
func AuditResourceTypeValues() []AuditResourceType {
	return []AuditResourceType{
		AuditResourceTypePayload,
		AuditResourceTypeUser,
		AuditResourceTypeDnsRecord,
		AuditResourceTypeHttpRoute,
	}
}

// String implements the Stringer interface.
func (x AuditResourceType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x AuditResourceType) IsValid() bool {
	_, err := ParseAuditResourceType(string(x))
	return err == nil
}

var _AuditResourceTypeValue = map[string]AuditResourceType{
	"payload":    AuditResourceTypePayload,
	"user":       AuditResourceTypeUser,
	"dns_record": AuditResourceTypeDnsRecord,
	"http_route": AuditResourceTypeHttpRoute,
}

// ParseAuditResourceType attempts to convert a string to a AuditResourceType.
func ParseAuditResourceType(name string) (AuditResourceType, error) {
	if x, ok := _AuditResourceTypeValue[name]; ok {
		return x, nil
	}
	return AuditResourceType(""), fmt.Errorf("%s is %w", name, ErrInvalidAuditResourceType)
}

func (x AuditResourceType) Ptr() *AuditResourceType {
	return &x
}

const (
	// AuditSourceApi is a AuditSource of type api.
	AuditSourceApi AuditSource = "api"
	// AuditSourceTelegram is a AuditSource of type telegram.
	AuditSourceTelegram AuditSource = "telegram"
	// AuditSourceLark is a AuditSource of type lark.
	AuditSourceLark AuditSource = "lark"
	// AuditSourceSlack is a AuditSource of type slack.
	AuditSourceSlack AuditSource = "slack"
)

var ErrInvalidAuditSource = fmt.Errorf("not a valid AuditSource, try [%s]", strings.Join(_AuditSourceNames, ", "))

var _AuditSourceNames = []string{
	string(AuditSourceApi),
	string(AuditSourceTelegram),
	string(AuditSourceLark),
	string(AuditSourceSlack),
}

// AuditSourceNames returns a list of possible string values of AuditSource.
func AuditSourceNames() []string {
	tmp := make([]string, len(_AuditSourceNames))
	copy(tmp, _AuditSourceNames)
	return tmp
}

// AuditSourceValues returns a list of the values for AuditSource
func AuditSourceValues() []AuditSource {
	return []AuditSource{
		AuditSourceApi,
		AuditSourceTelegram,
		AuditSourceLark,
		AuditSourceSlack,
	}
}

// String implements the Stringer interface.
func (x AuditSource) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x AuditSource) IsValid() bool {
	_, err := ParseAuditSource(string(x))
	return err == nil
}

var _AuditSourceValue = map[string]AuditSource{
	"api":      AuditSourceApi,
	"telegram": AuditSourceTelegram,
	"lark":     AuditSourceLark,
	"slack":    AuditSourceSlack,
}

// ParseAuditSource attempts to convert a string to a AuditSource.
func ParseAuditSource(name string) (AuditSource, error) {
	if x, ok := _AuditSourceValue[name]; ok {
		return x, nil
	}
	return AuditSource(""), fmt.Errorf("%s is %w", name, ErrInvalidAuditSource)
}

func (x AuditSource) Ptr() *AuditSource {
	return &x
}
