// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package service

import (
	"fmt"
	"strings"
)

const (
	// HTTPMethodGET is a HTTPMethod of type GET.
	HTTPMethodGET HTTPMethod = "GET"
	// HTTPMethodHEAD is a HTTPMethod of type HEAD.
	HTTPMethodHEAD HTTPMethod = "HEAD"
	// HTTPMethodPOST is a HTTPMethod of type POST.
	HTTPMethodPOST HTTPMethod = "POST"
	// HTTPMethodPUT is a HTTPMethod of type PUT.
	HTTPMethodPUT HTTPMethod = "PUT"
	// HTTPMethodPATCH is a HTTPMethod of type PATCH.
	HTTPMethodPATCH HTTPMethod = "PATCH"
	// HTTPMethodDELETE is a HTTPMethod of type DELETE.
	HTTPMethodDELETE HTTPMethod = "DELETE"
	// HTTPMethodCONNECT is a HTTPMethod of type CONNECT.
	HTTPMethodCONNECT HTTPMethod = "CONNECT"
	// HTTPMethodOPTIONS is a HTTPMethod of type OPTIONS.
	HTTPMethodOPTIONS HTTPMethod = "OPTIONS"
	// HTTPMethodTRACE is a HTTPMethod of type TRACE.
	HTTPMethodTRACE HTTPMethod = "TRACE"
	// HTTPMethodANY is a HTTPMethod of type ANY.
	HTTPMethodANY HTTPMethod = "ANY"
)

var ErrInvalidHTTPMethod = fmt.Errorf("not a valid HTTPMethod, try [%s]", strings.Join(_HTTPMethodNames, ", "))

var _HTTPMethodNames = []string{
	string(HTTPMethodGET),
	string(HTTPMethodHEAD),
	string(HTTPMethodPOST),
	string(HTTPMethodPUT),
	string(HTTPMethodPATCH),
	string(HTTPMethodDELETE),
	string(HTTPMethodCONNECT),
	string(HTTPMethodOPTIONS),
	string(HTTPMethodTRACE),
	string(HTTPMethodANY),
}

// HTTPMethodNames returns a list of possible string values of HTTPMethod.
func HTTPMethodNames() []string {
	tmp := make([]string, len(_HTTPMethodNames))
	copy(tmp, _HTTPMethodNames)
	return tmp
}

// HTTPMethodValues returns a list of the values for HTTPMethod
func HTTPMethodValues() []HTTPMethod {
	return []HTTPMethod{
		HTTPMethodGET,
		HTTPMethodHEAD,
		HTTPMethodPOST,
		HTTPMethodPUT,
		HTTPMethodPATCH,
		HTTPMethodDELETE,
		HTTPMethodCONNECT,
		HTTPMethodOPTIONS,
		HTTPMethodTRACE,
		HTTPMethodANY,
	}
}

// String implements the Stringer interface.
func (x HTTPMethod) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x HTTPMethod) IsValid() bool {
	_, err := ParseHTTPMethod(string(x))
	return err == nil
}

var _HTTPMethodValue = map[string]HTTPMethod{
	"GET":     HTTPMethodGET,
	"HEAD":    HTTPMethodHEAD,
	"POST":    HTTPMethodPOST,
	"PUT":     HTTPMethodPUT,
	"PATCH":   HTTPMethodPATCH,
	"DELETE":  HTTPMethodDELETE,
	"CONNECT": HTTPMethodCONNECT,
	"OPTIONS": HTTPMethodOPTIONS,
	"TRACE":   HTTPMethodTRACE,
	"ANY":     HTTPMethodANY,
}

// ParseHTTPMethod attempts to convert a string to a HTTPMethod.
func ParseHTTPMethod(name string) (HTTPMethod, error) {
	if x, ok := _HTTPMethodValue[name]; ok {
		return x, nil
	}
	return HTTPMethod(""), fmt.Errorf("%s is %w", name, ErrInvalidHTTPMethod)
}

func (x HTTPMethod) Ptr() *HTTPMethod {
	return &x
}
