// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package service

import (
	"fmt"
	"strings"
)

const (
	// AuditActionCreate is a AuditAction of type create.
	AuditActionCreate AuditAction = "create"
	// AuditActionUpdate is a AuditAction of type update.
	AuditActionUpdate AuditAction = "update"
	// AuditActionDelete is a AuditAction of type delete.
	AuditActionDelete AuditAction = "delete"
)

var ErrInvalidAuditAction = fmt.Errorf("not a valid AuditAction, try [%s]", strings.Join(_AuditActionNames, ", "))

var _AuditActionNames = []string{
	string(AuditActionCreate),
	string(AuditActionUpdate),
	string(AuditActionDelete),
}

// AuditActionNames returns a list of possible string values of AuditAction.
func AuditActionNames() []string {
	tmp := make([]string, len(_AuditActionNames))
	copy(tmp, _AuditActionNames)
	return tmp
}

// AuditActionValues returns a list of the values for AuditAction
func AuditActionValues() []AuditAction {
	return []AuditAction{
		AuditActionCreate,
		AuditActionUpdate,
		AuditActionDelete,
	}
}

// String implements the Stringer interface.
func (x AuditAction) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x AuditAction) IsValid() bool {
	_, err := ParseAuditAction(string(x))
	return err == nil
}

var _AuditActionValue = map[string]AuditAction{
	"create": AuditActionCreate,
	"update": AuditActionUpdate,
	"delete": AuditActionDelete,
}

// ParseAuditAction attempts to convert a string to a AuditAction.
func ParseAuditAction(name string) (AuditAction, error) {
	if x, ok := _AuditActionValue[name]; ok {
		return x, nil
	}
	return AuditAction(""), fmt.Errorf("%s is %w", name, ErrInvalidAuditAction)
}

func (x AuditAction) Ptr() *AuditAction {
	return &x
}

const (
	// AuditResourceTypePayload is a AuditResourceType of type payload.
	AuditResourceTypePayload AuditResourceType = "payload"
	// AuditResourceTypeUser is a AuditResourceType of type user.
	AuditResourceTypeUser AuditResourceType = "user"
	// AuditResourceTypeDnsRecord is a AuditResourceType of type dns_record.
	AuditResourceTypeDnsRecord AuditResourceType = "dns_record"
	// AuditResourceTypeHttpRoute is a AuditResourceType of type http_route.
	AuditResourceTypeHttpRoute AuditResourceType = "http_route"
)

var ErrInvalidAuditResourceType = fmt.Errorf("not a valid AuditResourceType, try [%s]", strings.Join(_AuditResourceTypeNames, ", "))

var _AuditResourceTypeNames = []string{
	string(AuditResourceTypePayload),
	string(AuditResourceTypeUser),
	string(AuditResourceTypeDnsRecord),
	string(AuditResourceTypeHttpRoute),
}

// AuditResourceTypeNames returns a list of possible string values of AuditResourceType.
func AuditResourceTypeNames() []string {
	tmp := make([]string, len(_AuditResourceTypeNames))
	copy(tmp, _AuditResourceTypeNames)
	return tmp
}

// AuditResourceTypeValues returns a list of the values for AuditResourceType
func AuditResourceTypeValues() []AuditResourceType {
	return []AuditResourceType{
		AuditResourceTypePayload,
		AuditResourceTypeUser,
		AuditResourceTypeDnsRecord,
		AuditResourceTypeHttpRoute,
	}
}

// String implements the Stringer interface.
func (x AuditResourceType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x AuditResourceType) IsValid() bool {
	_, err := ParseAuditResourceType(string(x))
	return err == nil
}

var _AuditResourceTypeValue = map[string]AuditResourceType{
	"payload":    AuditResourceTypePayload,
	"user":       AuditResourceTypeUser,
	"dns_record": AuditResourceTypeDnsRecord,
	"http_route": AuditResourceTypeHttpRoute,
}

// ParseAuditResourceType attempts to convert a string to a AuditResourceType.
func ParseAuditResourceType(name string) (AuditResourceType, error) {
	if x, ok := _AuditResourceTypeValue[name]; ok {
		return x, nil
	}
	return AuditResourceType(""), fmt.Errorf("%s is %w", name, ErrInvalidAuditResourceType)
}

func (x AuditResourceType) Ptr() *AuditResourceType {
	return &x
}

const (
	// AuditSourceApi is a AuditSource of type api.
	AuditSourceApi AuditSource = "api"
	// AuditSourceTelegram is a AuditSource of type telegram.
	AuditSourceTelegram AuditSource = "telegram"
	// AuditSourceLark is a AuditSource of type lark.
	AuditSourceLark AuditSource = "lark"
	// AuditSourceSlack is a AuditSource of type slack.
	AuditSourceSlack AuditSource = "slack"
)

var ErrInvalidAuditSource = fmt.Errorf("not a valid AuditSource, try [%s]", strings.Join(_AuditSourceNames, ", "))

var _AuditSourceNames = []string{
	string(AuditSourceApi),
	string(AuditSourceTelegram),
	string(AuditSourceLark),
	string(AuditSourceSlack),
}

// AuditSourceNames returns a list of possible string values of AuditSource.
func AuditSourceNames() []string {
	tmp := make([]string, len(_AuditSourceNames))
	copy(tmp, _AuditSourceNames)
	return tmp
}

// AuditSourceValues returns a list of the values for AuditSource
func AuditSourceValues() []AuditSource {
	return []AuditSource{
		AuditSourceApi,
		AuditSourceTelegram,
		AuditSourceLark,
		AuditSourceSlack,
	}
}

// String implements the Stringer interface.
func (x AuditSource) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x AuditSource) IsValid() bool {
	_, err := ParseAuditSource(string(x))
	return err == nil
}

var _AuditSourceValue = map[string]AuditSource{
	"api":      AuditSourceApi,
	"telegram": AuditSourceTelegram,
	"lark":     AuditSourceLark,
	"slack":    AuditSourceSlack,
}

// ParseAuditSource attempts to convert a string to a AuditSource.
func ParseAuditSource(name string) (AuditSource, error) {
	if x, ok := _AuditSourceValue[name]; ok {
		return x, nil
	}
	return AuditSource(""), fmt.Errorf("%s is %w", name, ErrInvalidAuditSource)
}

func (x AuditSource) Ptr() *AuditSource {
	return &x
}

const (
	// DNSRecordStrategyAll is a DNSRecordStrategy of type all.
	DNSRecordStrategyAll DNSRecordStrategy = "all"
	// DNSRecordStrategyRoundRobin is a DNSRecordStrategy of type round-robin.
	DNSRecordStrategyRoundRobin DNSRecordStrategy = "round-robin"
	// DNSRecordStrategyRebind is a DNSRecordStrategy of type rebind.
	DNSRecordStrategyRebind DNSRecordStrategy = "rebind"
)

var ErrInvalidDNSRecordStrategy = fmt.Errorf("not a valid DNSRecordStrategy, try [%s]", strings.Join(_DNSRecordStrategyNames, ", "))

var _DNSRecordStrategyNames = []string{
	string(DNSRecordStrategyAll),
	string(DNSRecordStrategyRoundRobin),
	string(DNSRecordStrategyRebind),
}

// DNSRecordStrategyNames returns a list of possible string values of DNSRecordStrategy.
func DNSRecordStrategyNames() []string {
	tmp := make([]string, len(_DNSRecordStrategyNames))
	copy(tmp, _DNSRecordStrategyNames)
	return tmp
}

// DNSRecordStrategyValues returns a list of the values for DNSRecordStrategy
func DNSRecordStrategyValues() []DNSRecordStrategy {
	return []DNSRecordStrategy{
		DNSRecordStrategyAll,
		DNSRecordStrategyRoundRobin,
		DNSRecordStrategyRebind,
	}
}

// String implements the Stringer interface.
func (x DNSRecordStrategy) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x DNSRecordStrategy) IsValid() bool {
	_, err := ParseDNSRecordStrategy(string(x))
	return err == nil
}

var _DNSRecordStrategyValue = map[string]DNSRecordStrategy{
	"all":         DNSRecordStrategyAll,
	"round-robin": DNSRecordStrategyRoundRobin,
	"rebind":      DNSRecordStrategyRebind,
}

// ParseDNSRecordStrategy attempts to convert a string to a DNSRecordStrategy.
func ParseDNSRecordStrategy(name string) (DNSRecordStrategy, error) {
	if x, ok := _DNSRecordStrategyValue[name]; ok {
		return x, nil
	}
	return DNSRecordStrategy(""), fmt.Errorf("%s is %w", name, ErrInvalidDNSRecordStrategy)
}

func (x DNSRecordStrategy) Ptr() *DNSRecordStrategy {
	return &x
}

const (
	// DNSRecordTypeA is a DNSRecordType of type A.
	DNSRecordTypeA DNSRecordType = "A"
	// DNSRecordTypeAAAA is a DNSRecordType of type AAAA.
	DNSRecordTypeAAAA DNSRecordType = "AAAA"
	// DNSRecordTypeMX is a DNSRecordType of type MX.
	DNSRecordTypeMX DNSRecordType = "MX"
	// DNSRecordTypeTXT is a DNSRecordType of type TXT.
	DNSRecordTypeTXT DNSRecordType = "TXT"
	// DNSRecordTypeCNAME is a DNSRecordType of type CNAME.
	DNSRecordTypeCNAME DNSRecordType = "CNAME"
	// DNSRecordTypeNS is a DNSRecordType of type NS.
	DNSRecordTypeNS DNSRecordType = "NS"
	// DNSRecordTypeCAA is a DNSRecordType of type CAA.
	DNSRecordTypeCAA DNSRecordType = "CAA"
)

var ErrInvalidDNSRecordType = fmt.Errorf("not a valid DNSRecordType, try [%s]", strings.Join(_DNSRecordTypeNames, ", "))

var _DNSRecordTypeNames = []string{
	string(DNSRecordTypeA),
	string(DNSRecordTypeAAAA),
	string(DNSRecordTypeMX),
	string(DNSRecordTypeTXT),
	string(DNSRecordTypeCNAME),
	string(DNSRecordTypeNS),
	string(DNSRecordTypeCAA),
}

// DNSRecordTypeNames returns a list of possible string values of DNSRecordType.
func DNSRecordTypeNames() []string {
	tmp := make([]string, len(_DNSRecordTypeNames))
	copy(tmp, _DNSRecordTypeNames)
	return tmp
}

// DNSRecordTypeValues returns a list of the values for DNSRecordType
func DNSRecordTypeValues() []DNSRecordType {
	return []DNSRecordType{
		DNSRecordTypeA,
		DNSRecordTypeAAAA,
		DNSRecordTypeMX,
		DNSRecordTypeTXT,
		DNSRecordTypeCNAME,
		DNSRecordTypeNS,
		DNSRecordTypeCAA,
	}
}

// String implements the Stringer interface.
func (x DNSRecordType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x DNSRecordType) IsValid() bool {
	_, err := ParseDNSRecordType(string(x))
	return err == nil
}

var _DNSRecordTypeValue = map[string]DNSRecordType{
	"A":     DNSRecordTypeA,
	"AAAA":  DNSRecordTypeAAAA,
	"MX":    DNSRecordTypeMX,
	"TXT":   DNSRecordTypeTXT,
	"CNAME": DNSRecordTypeCNAME,
	"NS":    DNSRecordTypeNS,
	"CAA":   DNSRecordTypeCAA,
}

// ParseDNSRecordType attempts to convert a string to a DNSRecordType.
func ParseDNSRecordType(name string) (DNSRecordType, error) {
	if x, ok := _DNSRecordTypeValue[name]; ok {
		return x, nil
	}
	return DNSRecordType(""), fmt.Errorf("%s is %w", name, ErrInvalidDNSRecordType)
}

func (x DNSRecordType) Ptr() *DNSRecordType {
	return &x
}

const (
	// EventProtocolDns is a EventProtocol of type dns.
	EventProtocolDns EventProtocol = "dns"
	// EventProtocolHttp is a EventProtocol of type http.
	EventProtocolHttp EventProtocol = "http"
	// EventProtocolHttps is a EventProtocol of type https.
	EventProtocolHttps EventProtocol = "https"
	// EventProtocolSmtp is a EventProtocol of type smtp.
	EventProtocolSmtp EventProtocol = "smtp"
	// EventProtocolFtp is a EventProtocol of type ftp.
	EventProtocolFtp EventProtocol = "ftp"
)

var ErrInvalidEventProtocol = fmt.Errorf("not a valid EventProtocol, try [%s]", strings.Join(_EventProtocolNames, ", "))

var _EventProtocolNames = []string{
	string(EventProtocolDns),
	string(EventProtocolHttp),
	string(EventProtocolHttps),
	string(EventProtocolSmtp),
	string(EventProtocolFtp),
}

// EventProtocolNames returns a list of possible string values of EventProtocol.
func EventProtocolNames() []string {
	tmp := make([]string, len(_EventProtocolNames))
	copy(tmp, _EventProtocolNames)
	return tmp
}

// EventProtocolValues returns a list of the values for EventProtocol
func EventProtocolValues() []EventProtocol {
	return []EventProtocol{
		EventProtocolDns,
		EventProtocolHttp,
		EventProtocolHttps,
		EventProtocolSmtp,
		EventProtocolFtp,
	}
}

// String implements the Stringer interface.
func (x EventProtocol) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x EventProtocol) IsValid() bool {
	_, err := ParseEventProtocol(string(x))
	return err == nil
}

var _EventProtocolValue = map[string]EventProtocol{
	"dns":   EventProtocolDns,
	"http":  EventProtocolHttp,
	"https": EventProtocolHttps,
	"smtp":  EventProtocolSmtp,
	"ftp":   EventProtocolFtp,
}

// ParseEventProtocol attempts to convert a string to a EventProtocol.
func ParseEventProtocol(name string) (EventProtocol, error) {
	if x, ok := _EventProtocolValue[name]; ok {
		return x, nil
	}
	return EventProtocol(""), fmt.Errorf("%s is %w", name, ErrInvalidEventProtocol)
}

func (x EventProtocol) Ptr() *EventProtocol {
	return &x
}

const (
	// HTTPMethodGET is a HTTPMethod of type GET.
	HTTPMethodGET HTTPMethod = "GET"
	// HTTPMethodHEAD is a HTTPMethod of type HEAD.
	HTTPMethodHEAD HTTPMethod = "HEAD"
	// HTTPMethodPOST is a HTTPMethod of type POST.
	HTTPMethodPOST HTTPMethod = "POST"
	// HTTPMethodPUT is a HTTPMethod of type PUT.
	HTTPMethodPUT HTTPMethod = "PUT"
	// HTTPMethodPATCH is a HTTPMethod of type PATCH.
	HTTPMethodPATCH HTTPMethod = "PATCH"
	// HTTPMethodDELETE is a HTTPMethod of type DELETE.
	HTTPMethodDELETE HTTPMethod = "DELETE"
	// HTTPMethodCONNECT is a HTTPMethod of type CONNECT.
	HTTPMethodCONNECT HTTPMethod = "CONNECT"
	// HTTPMethodOPTIONS is a HTTPMethod of type OPTIONS.
	HTTPMethodOPTIONS HTTPMethod = "OPTIONS"
	// HTTPMethodTRACE is a HTTPMethod of type TRACE.
	HTTPMethodTRACE HTTPMethod = "TRACE"
	// HTTPMethodANY is a HTTPMethod of type ANY.
	HTTPMethodANY HTTPMethod = "ANY"
)

var ErrInvalidHTTPMethod = fmt.Errorf("not a valid HTTPMethod, try [%s]", strings.Join(_HTTPMethodNames, ", "))

var _HTTPMethodNames = []string{
	string(HTTPMethodGET),
	string(HTTPMethodHEAD),
	string(HTTPMethodPOST),
	string(HTTPMethodPUT),
	string(HTTPMethodPATCH),
	string(HTTPMethodDELETE),
	string(HTTPMethodCONNECT),
	string(HTTPMethodOPTIONS),
	string(HTTPMethodTRACE),
	string(HTTPMethodANY),
}

// HTTPMethodNames returns a list of possible string values of HTTPMethod.
func HTTPMethodNames() []string {
	tmp := make([]string, len(_HTTPMethodNames))
	copy(tmp, _HTTPMethodNames)
	return tmp
}

// HTTPMethodValues returns a list of the values for HTTPMethod
func HTTPMethodValues() []HTTPMethod {
	return []HTTPMethod{
		HTTPMethodGET,
		HTTPMethodHEAD,
		HTTPMethodPOST,
		HTTPMethodPUT,
		HTTPMethodPATCH,
		HTTPMethodDELETE,
		HTTPMethodCONNECT,
		HTTPMethodOPTIONS,
		HTTPMethodTRACE,
		HTTPMethodANY,
	}
}

// String implements the Stringer interface.
func (x HTTPMethod) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x HTTPMethod) IsValid() bool {
	_, err := ParseHTTPMethod(string(x))
	return err == nil
}

var _HTTPMethodValue = map[string]HTTPMethod{
	"GET":     HTTPMethodGET,
	"HEAD":    HTTPMethodHEAD,
	"POST":    HTTPMethodPOST,
	"PUT":     HTTPMethodPUT,
	"PATCH":   HTTPMethodPATCH,
	"DELETE":  HTTPMethodDELETE,
	"CONNECT": HTTPMethodCONNECT,
	"OPTIONS": HTTPMethodOPTIONS,
	"TRACE":   HTTPMethodTRACE,
	"ANY":     HTTPMethodANY,
}

// ParseHTTPMethod attempts to convert a string to a HTTPMethod.
func ParseHTTPMethod(name string) (HTTPMethod, error) {
	if x, ok := _HTTPMethodValue[name]; ok {
		return x, nil
	}
	return HTTPMethod(""), fmt.Errorf("%s is %w", name, ErrInvalidHTTPMethod)
}

func (x HTTPMethod) Ptr() *HTTPMethod {
	return &x
}

const (
	// ProtoCategoryDns is a ProtoCategory of type dns.
	ProtoCategoryDns ProtoCategory = "dns"
	// ProtoCategoryHttp is a ProtoCategory of type http.
	ProtoCategoryHttp ProtoCategory = "http"
	// ProtoCategorySmtp is a ProtoCategory of type smtp.
	ProtoCategorySmtp ProtoCategory = "smtp"
	// ProtoCategoryFtp is a ProtoCategory of type ftp.
	ProtoCategoryFtp ProtoCategory = "ftp"
)

var ErrInvalidProtoCategory = fmt.Errorf("not a valid ProtoCategory, try [%s]", strings.Join(_ProtoCategoryNames, ", "))

var _ProtoCategoryNames = []string{
	string(ProtoCategoryDns),
	string(ProtoCategoryHttp),
	string(ProtoCategorySmtp),
	string(ProtoCategoryFtp),
}

// ProtoCategoryNames returns a list of possible string values of ProtoCategory.
func ProtoCategoryNames() []string {
	tmp := make([]string, len(_ProtoCategoryNames))
	copy(tmp, _ProtoCategoryNames)
	return tmp
}

// ProtoCategoryValues returns a list of the values for ProtoCategory
func ProtoCategoryValues() []ProtoCategory {
	return []ProtoCategory{
		ProtoCategoryDns,
		ProtoCategoryHttp,
		ProtoCategorySmtp,
		ProtoCategoryFtp,
	}
}

// String implements the Stringer interface.
func (x ProtoCategory) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ProtoCategory) IsValid() bool {
	_, err := ParseProtoCategory(string(x))
	return err == nil
}

var _ProtoCategoryValue = map[string]ProtoCategory{
	"dns":  ProtoCategoryDns,
	"http": ProtoCategoryHttp,
	"smtp": ProtoCategorySmtp,
	"ftp":  ProtoCategoryFtp,
}

// ParseProtoCategory attempts to convert a string to a ProtoCategory.
func ParseProtoCategory(name string) (ProtoCategory, error) {
	if x, ok := _ProtoCategoryValue[name]; ok {
		return x, nil
	}
	return ProtoCategory(""), fmt.Errorf("%s is %w", name, ErrInvalidProtoCategory)
}

func (x ProtoCategory) Ptr() *ProtoCategory {
	return &x
}
