// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package service

import (
	"fmt"
	"strings"
)

const (
	// ProtoCategoryDns is a ProtoCategory of type dns.
	ProtoCategoryDns ProtoCategory = "dns"
	// ProtoCategoryHttp is a ProtoCategory of type http.
	ProtoCategoryHttp ProtoCategory = "http"
	// ProtoCategorySmtp is a ProtoCategory of type smtp.
	ProtoCategorySmtp ProtoCategory = "smtp"
	// ProtoCategoryFtp is a ProtoCategory of type ftp.
	ProtoCategoryFtp ProtoCategory = "ftp"
)

var ErrInvalidProtoCategory = fmt.Errorf("not a valid ProtoCategory, try [%s]", strings.Join(_ProtoCategoryNames, ", "))

var _ProtoCategoryNames = []string{
	string(ProtoCategoryDns),
	string(ProtoCategoryHttp),
	string(ProtoCategorySmtp),
	string(ProtoCategoryFtp),
}

// ProtoCategoryNames returns a list of possible string values of ProtoCategory.
func ProtoCategoryNames() []string {
	tmp := make([]string, len(_ProtoCategoryNames))
	copy(tmp, _ProtoCategoryNames)
	return tmp
}

// ProtoCategoryValues returns a list of the values for ProtoCategory
func ProtoCategoryValues() []ProtoCategory {
	return []ProtoCategory{
		ProtoCategoryDns,
		ProtoCategoryHttp,
		ProtoCategorySmtp,
		ProtoCategoryFtp,
	}
}

// String implements the Stringer interface.
func (x ProtoCategory) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ProtoCategory) IsValid() bool {
	_, err := ParseProtoCategory(string(x))
	return err == nil
}

var _ProtoCategoryValue = map[string]ProtoCategory{
	"dns":  ProtoCategoryDns,
	"http": ProtoCategoryHttp,
	"smtp": ProtoCategorySmtp,
	"ftp":  ProtoCategoryFtp,
}

// ParseProtoCategory attempts to convert a string to a ProtoCategory.
func ParseProtoCategory(name string) (ProtoCategory, error) {
	if x, ok := _ProtoCategoryValue[name]; ok {
		return x, nil
	}
	return ProtoCategory(""), fmt.Errorf("%s is %w", name, ErrInvalidProtoCategory)
}

func (x ProtoCategory) Ptr() *ProtoCategory {
	return &x
}

// MarshalText implements the text marshaller method.
func (x ProtoCategory) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ProtoCategory) UnmarshalText(text []byte) error {
	tmp, err := ParseProtoCategory(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ProtoCategory) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
