name: Test docs deployment

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./docs

jobs:
  test-deploy:
    name: Test docs deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: npm
          cache-dependency-path: ./docs/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Test build website
        run: npm run build
